whill:
  ros__parameters:
    port_name: "/dev/ttyUSB0"
    whill_publish_interval_ms: 100
    odom_publish_interval_ms: 30
    publish_odom_tf: false
    odom_frame_id: "odom"
    base_frame_id: "base_link"